Installation of jupyter :
    
    pip install notebook
    
    python -m pip install notebook #--> python 2 
    
    py -m pip install notebook #----> python 3
    
    
    Visual studio code -> Terminal -> CD to Working folder 
        1.jupyter notebook
        2.python -m notebook / py -m notebook (alt)
    
Anaconda - > https://docs.anaconda.com/anaconda

conda list

conda create --name interview python matplotlib numpy pandas seaborn basemap scikit-learn --> Creating an environment 
refer : https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands

conda env list --> list out all the env u created 
    
conda create --name interview --clone interviewdspt2  ---> cloning env
Deactivate --> conda deactivate
Activating the conda env -->       conda activate interviewdspt2

In [ ]:
Numpy - Numerical python open source library 

homogeneous --> same data types (Faster)

hetero -> Structured Data  

name=np.array(['a','b','c'])
age=np.array([1,2,3])
weight=np.array([20.0,30.5,18.5])

data= np.zeros(3, dtype={'names':('name','age','weight'),
                         'formats':('U10','i4','f8')})
print(data.dtype)


In [19]:
#pip install numpy
import numpy as np
print(np.__version__)

a=np.array(['a','b'])
print(a)

#create a 2 d array
t=np.array([[1,2],[3,4]])

print(t.shape)
print(t.size)
print(t.dtype)
print(t.ndim)

#accessing
three=np.array([[[1,2,3],[1,4,5]],[[4,5,6],[7,8,9]]])
print(three[1,0,2])

#slicing
o=np.array([1,2,3,4,5,6,7,8,9,10])
print(o[::3]) #skip the third value
print (o[::-1])#reverse the array 
print(o.reshape(2,5))#reshape to 2d
ss=np.split(o,2)#split 2 data
print(ss[0])
print(ss[1])

#mean , std , median
print(np.mean(o))
print(np.std(o))
print(np.median(o))

#bits

#invert , left shit , right shfit
print(np.invert(o))
print(np.left_shift(o,1))
print(np.right_shift(o,1))


1.23.5
['a' 'b']
(2, 2)
4
int32
2
6
[ 1  4  7 10]
[10  9  8  7  6  5  4  3  2  1]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5]
[ 6  7  8  9 10]
5.5
2.8722813232690143
5.5
[ -2  -3  -4  -5  -6  -7  -8  -9 -10 -11]
[ 2  4  6  8 10 12 14 16 18 20]
[0 1 1 2 2 3 3 4 4 5]


Task:
You are given a X integer array matrix with space separated elements ( = rows and  = columns).
Your task is to print the transpose and flatten results.
Input Format:
The first line contains the space separated values of  and .
The next  lines contains the space separated elements of  columns.
Output Format:
First, print the transpose array and then print the flatten.
Sample Input:
2 2
1 2
3 4
Sample Output:
[[1 3]
 [2 4]]
[1 2 3 4]

In [31]:
import numpy as np

arr= np.array([[2,1,3],[2,2,4]]) #2*3
print(arr)
Input=np.transpose(arr) #3*2
print(Input)
print(np.transpose(Input))


[[2 1 3]
 [2 2 4]]
[[2 2]
 [1 2]
 [3 4]]
[[2 1 3]
 [2 2 4]]
